'# S4 layers':
    value: 6
_wandb:
    value:
        cli_version: 0.23.1
        e:
            89iqe8fqb6hv0toauh02e39rwj59qy30:
                codePath: scripts/training/train_s4_mae.py
                codePathLocal: train_s4_mae.py
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3786719797248"
                        used: "1570446544896"
                email: emilyzho@usc.edu
                executable: /home/emilyzho/miniconda3/envs/ssl-physio/bin/python3
                git:
                    commit: 3d53e2ea33f83cb61b8f2d5fdbee84d7aede0abd
                    remote: git@github.com:emilyxzhou/ssl-physio.git
                gpu: NVIDIA RTX 6000 Ada Generation
                gpu_count: 4
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-ed049f0f-f637-a8ab-edee-4c0db027e1ff
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-b6570130-b857-8fb2-abbe-aed916587465
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-fb25071d-102a-5058-1335-75b66616bbbf
                    - architecture: Ada
                      cudaCores: 18176
                      memoryTotal: "51527024640"
                      name: NVIDIA RTX 6000 Ada Generation
                      uuid: GPU-4abdc09f-9770-fd03-54fe-09cc838dde47
                host: redondo
                memory:
                    total: "270060945408"
                os: Linux-6.8.0-86-generic-x86_64-with-glibc2.39
                program: /home/emilyzho/ssl-physio/scripts/training/./train_s4_mae.py
                python: CPython 3.12.12
                root: /home/emilyzho/ssl-physio/scripts/training
                startedAt: "2026-01-04T21:48:55.999863Z"
                writerId: 89iqe8fqb6hv0toauh02e39rwj59qy30
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
S4 dim:
    value: 128
d_output:
    value: 128
decoder:
    value:
        - 128
        - 64
        - 32
encoder:
    value: null
epochs:
    value: 50
learning rate:
    value: 0.0005
masking ratio:
    value: 0.5
mode:
    value: full
optimizer:
    value: AdamW
reconstruction:
    value: full
save path:
    value: /home/emilyzho/ssl-physio/models/reconstruction/s4-mae_2026-01-04_21:48:55.pt
scaling:
    value: mean
