mode: full
# mode: heart rate
# mode: step count

reconstruction: full
# reconstruction: heart rate

scale: mean
# scale: median
# scale: scale
# scale: global mean

d_input: 2
d_model: 128    # If dec_hidden_dims is not None, d_model must equal the last hidden dim
d_output: 128

# enc_hidden_dims: [32, 64]
enc_hidden_dims: null

dec_hidden_dims: [128, 64, 32]
# dec_hidden_dims: null

decoder_type: deconv

n_layers_s4: 6

mask_ratio: 0.1

sequence_len: 1440

lr: 0.0005